version: "1"
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: admin:prod
    container_name: medusa-admin
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    ports:
      - "7000:7000"

volumes:
  node_modules:
networks:
  default:
